### ISSUE TITLE
Pointcloud grad cam for  3d Object detection module 

### ISSUE THREAD

**Issue by abhigoku10** [Fragjacker/Pointcloud-grad-CAM#4]
@Fragjacker  my current architecture is below 
![image](https://user-images.githubusercontent.com/22094053/95979519-5fe99380-0e39-11eb-98dc-1dfdbc20cd31.png)

can we use the same concept you have mentioned and extend for this network

**Comment by Fragjacker** [comment]
Should be possible, yes. Depending on what you want to investigate, you have to do a tiny modification of your model so that it returns the matrices of interest and then compute the gradient so that you get the weights for each point. Depending on your architecture you will have to alter the implementation to match the specifications of your problem. The original p-grad-CAM was used to visualize the reasoning behind object classification tasks. Since you do segmentation and center estimation you will also have to modify the function to compute the gradient as well so that you get meaningful outputs, fitting your problem.
