### ISSUE TITLE
could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by devskroy1** [Fragjacker/Pointcloud-grad-CAM#6]
Hi,

I have created a conda environment using your p-grad-CAM.yml file.
After activating the environment, when I run `python train.py`, I get the following error when `sess.run()` is called on line 234 in the train.py file (inside `train_one_epoch()` function):

```
could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)
```

I am using:
CUDA 9.0
Cudnn 7.3.1
Ubuntu 20.04
Python v3.5.6 Anaconda Inc.

I am training on a GPU.

This might be due to my running out of memory on the GPU, I checked if `config.gpu_options.allow_growth` is set to True, and it is. I also tried `gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.7)` but I still get the same error.

Do you know how I could resolve this issue?

Thanks

**Comment by Fragjacker** [comment]
The issue you reported sounds like a system issue. I have looked around and found this:

https://stackoverflow.com/questions/43147983/could-not-create-cudnn-handle-cudnn-status-internal-error

https://github.com/tensorflow/tensorflow/issues/16965

Apparently the cause of the issue is the GPU running out of memory or the GPU drivers causing issues on Ubuntu.

The specs you listed look OK to me.

**Comment by devskroy1** [comment]
Thanks for your reply.
I have now resolved the issue, it was due to the GPU running out of memory.
